### ISSUE TITLE
PS/1 Audio Card not detected on PS/1 2121 with Joe Montana Football game

### ISSUE THREAD

**Issue by Fenix770** [barotto/IBMulator#24]
Hello!

I tested the DOS game "Joe Montana Football" and it does not detect the PS/1 Audicard with PS/1 2121 emulation. However, with PS/1 2011, it detects correctly the card.

~~PD:  I, also, could not change correctly the RAM memory amount in PS/1 2121 machine. If put 2mb in the ini file it it still says 2048kb (instead of 4096kb) at startup but DOS mem command says there is 14mb of XMS available.~~

**Comment by barotto** [comment]
Thank you for testing and reporting!
I'll investigate.

**Comment by barotto** [comment]
Regarding the second part of the question (wrong memory reported), I can't reproduce the issue. Keep in mind that the correct value for the "expansion" config is 2M and not 2mb (uppercase M). Maybe I should make the program less picky...

**Comment by barotto** [comment]
This is not an IBMulator issue.
I've tested "Joe Montana Football" on my real PS/1 2121 with the PS/1 Sound Card installed and the game does not detect it.
Some games can't detect the sound card on the 2121 (Prince of Persia is another example), some others can (the PS/1 version of Silpheed for example).
I suspect the games that can't detect the audio card do a machine model check and when they read F8h instead of the expected FCh they don't go any further, assuming that it's not a PS/1.
