### ISSUE TITLE
operating without HD

### ISSUE THREAD

**Issue by blindphoneman** [barotto/IBMulator#68]
Hi:

I was reading the manual and, apparently, there was a system without an HD at the time.

I wanted to experience the system without the HD.

I tried removing the HD (setting HD=none), but, I got 2 beeps.

I am totally blind, so am not sure what the error was as my gui didn't read it properly.

Am I doing something wrong?

Closest I came was actually using debug to remove all partitions on the HD, then, it boots into the ROMshell.

Is that the only way to do this/

Thanks!

**Comment by barotto** [comment]
Hi

the 2 beeps are emitted by the PS/1 BIOS during the initial testing phase when it detects a problem.

In this case the problem is that the configuration changed and is now different from what is memorized in the CMOS memory.

On the screen there's a numeric error code (162)

To continue booting you need to press F1. The system will then work just fine.

You will ear the 2 beeps every time you boot the system until you run the program CONFIGUR.EXE
