### ISSUE TITLE
Hacking the ROM BIOS for date and clock format?

### ISSUE THREAD

**Issue by WishBeer** [barotto/IBMulator#84]
Is it possible to hack the ROM for viewing date and clock mm.dd.yy and 24 hour clock independent of rom language?

**Comment by barotto** [comment]
Dates are formatted using the [COUNTRY.SYS](http://manmrk.net/tutorials/DOS/help/country.htm) command.
I think all you have to do is add a suitable country line in `C:\CONFIG.SYS`, then set the CMOS to force the PS/1 to load CONFIG.SYS from C: using `CUSTOMIZ.EXE`.
However I'm not sure there's a setting for mm.dd.yy with 24h clocks. Otherwise you would need to alter the ROMSHELL.COM program to do exactly that.

**Comment by WishBeer** [comment]
When I changed the code in the line that sets the country code according to that ROM's country in the ROM file, I got the result I wanted. Changing the `config.sys `country code does not change the date/time format on the 4 quad screen, only the change is observed when switching to DOS.
